version: '3'
x-mongo-conf: &mongo_conf
  image: mongo:7.0.6-jammy
  volumes:
  - ./mongod.conf:/etc/mongo/mongod.conf
  command:
  - "--config"
  - "/etc/mongo/mongod.conf"
services:
  rs7mongo1:
    <<: *mongo_conf
  rs7mongo2:
    <<: *mongo_conf
  rs7mongo3:
    <<: *mongo_conf
